name: main action
on:
  push:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]
env:
  IMAGE_NAME: image183
jobs:
  build_web:
    name: 編譯程式
    runs-on: ubuntu-latest
    outputs:
      BUILD_VERSION: ${{ steps.generate_build_version.outputs.build_version }}
    steps:
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '1 day'
      - name: 檢查分支
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: 產生版本號
        id: generate_build_version
        run: |
          BUILD_VERSION=1.0.`git rev-list HEAD --count`.$GITHUB_RUN_NUMBER
          echo "::set-output name=build_version::$BUILD_VERSION"
          echo "$IMAGE_NAME:$BUILD_VERSION"
          echo "::set-output name=changed_lockfile::`git diff-tree --no-commit-id --name-only HEAD | grep '\.github`"

      - name: 變數
        run: echo $steps.generate_build_version.outputs.changed_lockfile

      - name: 結果
        if: ${{ steps.generate_build_version.outputs.changed_lockfile }}
        run: echo in



  
